services:
  postgres:
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=customers
      - POSTGRES_USER=carlos
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
